services:
  app:
    build: .
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/wallet
      JWT_SECRET: test
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && npm run start"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - default
  database:
    container_name: "database"
    image: "postgres"
    ports: 
      - "5432:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}